### ISSUE TITLE
OpenScad code generation for solids: need "center" option

### ISSUE THREAD

**Issue by yxqd** [mcvine/SCADGen#10]
@ilumsden @granrothge 

I just realized that openscad has a different convention in rendering solids than mcvine by default. For example, the following code in openscad
```
cube(10, 30, 40);
```
shows a block in the first octant. But in mcvine, the block should be centered at the origin.

The following code is correct:
```
cube(10, 30, 40, center=true);
```
@ilumsden, could you please fix the code for all the solids? Thanks.

**Comment by ilumsden** [comment]
Yeah, I'll get on that.

**Comment by ilumsden** [comment]
@yxqd should the Pyramid object also be centered at the origin, or should its vertex be at the origin?

**Comment by ilumsden** [comment]
I've updated all the tests to comply with the new centering. However, I wasn't able to figure out how to fix the `test5.xml` test in `comp_tests`.

**Comment by yxqd** [comment]
@ilumsden pyramid still has its tip at origin
