### ISSUE TITLE
Implement Travis CI

### ISSUE THREAD

**Issue by ilumsden** [mcvine/SCADGen#12]
Finish implementing Travis CI for the repo.
The main part that's left is finishing the .travis.yml file.

This issue is mostly being opened so that I can have something counting towards its completion in the SCADGen v0.1 milestone.

**Comment by yxqd** [comment]
Hi @ilumsden I made some changes to .travis.yml to make it work up to the point just before the installation and testing of SCADgen. And it is merged to master now. Please make sure to pull from origin the master and the travis branch before continuing. 

Here are the changes: https://github.com/mcvine/SCADGen/compare/363fb1ff258e131a113e4e0acf3807d8ebd63f40...e59a6bf249e1b157b42038e7eb1d13d3db35d6b5
