### ISSUE TITLE
Pytest: generateSCAD test saying "}" != "}"

### ISSUE THREAD

**Issue by ilumsden** [mcvine/SCADGen#3]
For some reason, the `test_generateSCAD` pytest is saying that the two files being compared are not equal. However, when examining the files by hand, it is clear that the files are identical. Using `diff -u`, the issue appears to be the final `}` of the files.

The files in question are `/SCADGen/test/pytest/test_xmls/parser_sol.scad` and `/SCADGen/test/pytest/test_xmls/parser_test.scad`.

The content produced by running the `diff -u` command is shown below:
```
> diff -u parser_sol.scad parser_test.scad

@@ -3,4 +3,4 @@
     translate([0.0, 0.0, -2.5]) {
     cylinder(h = 10.0, r = 1.5, $fn=100);
 }
-}
+}
\ No newline at end of file
```

**Comment by yxqd** [comment]
Could it be that  the newline is the difference?
