### ISSUE TITLE
implement pyramid as it is now implemented in Mcvine

### ISSUE THREAD

**Issue by granrothge** [mcvine/SCADGen#4]
See the following pull requests for more information.
https://github.com/mcvine/mcvine/pull/275
https://github.com/mcvine/mcvine/pull/276

**Comment by yxqd** [comment]
Please see https://github.com/mcvine/mcvine/blob/a6b9698dfa4056e81737b6bae7e3b0e29b2a7d3a/packages/mccomposite/lib/geometry/primitives/Pyramid.h#L14

The pyramid is defined by its height along z, and its dimensions along x and y (edgeX and edgeY). Its tip is at origin, and its tip is pointing up and its base is parallel to the x-y plane. The center of its base is at (0,0,-h).

**Comment by ilumsden** [comment]
Closed by #5
